---
steps:
  - name: 'node:8.16.2-onbuild'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -x
        npm install -g firebase-tools
        firebase deploy --project $PROJECT_ID --only hosting:flaxie
