steps:
- name: 'gcr.io/cloud-builders/npm'
  id: 'npm install'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  id: 'deploy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -x
    npm install -g firebase-tools
    firebase deploy --project $PROJECT_ID
